"""
Lynx C# Code Generator

Generates C# scripts for Dynamic Device Lynx liquid handling systems.
Based on the provided Lynx C# template for tip selection and automation.
"""

from typing import Dict, Any, List, Optional
import logging
from datetime import datetime


class LynxCodeGenerator:
    """Generates C# scripts for Dynamic Device Lynx systems"""
    
    def __init__(self):
        self.logger = logging.getLogger("catalyze.lynx_generator")
        
    def generate_lynx_script(self, instructions: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Generate a Lynx C# script based on protocol instructions
        
        Args:
            instructions: Protocol instructions from user
            context: Additional context (conversation history, etc.)
            
        Returns:
            Dictionary containing the generated C# code and metadata
        """
        
        try:
            self.logger.info(f"Generating Lynx C# script for: {instructions[:100]}...")
            
            # Parse instructions to extract protocol details
            protocol_info = self._parse_protocol_instructions(instructions, context)
            
            # Generate the C# script
            csharp_code = self._generate_csharp_template(protocol_info)
            
            return {
                "success": True,
                "code": csharp_code,
                "platform": "lynx",
                "language": "csharp",
                "timestamp": datetime.now().isoformat(),
                "protocol_info": protocol_info
            }
            
        except Exception as e:
            self.logger.error(f"Lynx code generation failed: {e}")
            return {
                "success": False,
                "error": str(e),
                "platform": "lynx",
                "language": "csharp",
                "timestamp": datetime.now().isoformat()
            }
    
    def _parse_protocol_instructions(self, instructions: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        """Parse protocol instructions to extract relevant information"""
        
        # Basic protocol information extraction
        protocol_info = {
            "title": "Generated Protocol",
            "description": instructions,
            "operations": [],
            "tip_operations": [],
            "liquid_handling": [],
            "plate_operations": []
        }
        
        # Extract operations from instructions
        instructions_lower = instructions.lower()
        
        # Look for common protocol operations
        if "pipette" in instructions_lower or "transfer" in instructions_lower:
            protocol_info["operations"].append("liquid_transfer")
            protocol_info["liquid_handling"].append("pipetting")
            
        if "tip" in instructions_lower or "pickup" in instructions_lower:
            protocol_info["operations"].append("tip_handling")
            protocol_info["tip_operations"].append("tip_pickup")
            
        if "plate" in instructions_lower or "well" in instructions_lower:
            protocol_info["operations"].append("plate_handling")
            protocol_info["plate_operations"].append("plate_manipulation")
            
        if "mix" in instructions_lower or "vortex" in instructions_lower:
            protocol_info["operations"].append("mixing")
            protocol_info["liquid_handling"].append("mixing")
            
        if "aspirate" in instructions_lower:
            protocol_info["liquid_handling"].append("aspiration")
            
        if "dispense" in instructions_lower:
            protocol_info["liquid_handling"].append("dispensing")
            
        # Extract volumes if mentioned
        import re
        volume_pattern = r'(\d+(?:\.\d+)?)\s*(?:μl|ul|microliter|microliters)'
        volumes = re.findall(volume_pattern, instructions_lower)
        if volumes:
            protocol_info["volumes"] = [float(v) for v in volumes]
            
        # Extract well positions if mentioned
        well_pattern = r'([A-H]\d{1,2})'
        wells = re.findall(well_pattern, instructions)
        if wells:
            protocol_info["well_positions"] = wells
            
        return protocol_info
    
    def _generate_csharp_template(self, protocol_info: Dict[str, Any]) -> str:
        """Generate the C# script template based on protocol information"""
        
        # Extract basic info
        title = protocol_info.get("title", "Generated Protocol")
        description = protocol_info.get("description", "Automated protocol generated by Catalyze")
        operations = protocol_info.get("operations", [])
        
        # Generate the C# script
        csharp_code = f'''using System;
using System.Collections.Generic;
using System.Windows.Forms;
using System.Drawing;
using MethodManager.Core;
using MMScriptObjects;
using MethodManager.Interop;
using MMScriptObjects.ScriptUtils;

// ============================================================================
// GENERATED PROTOCOL: {title}
// ============================================================================
// Description: {description}
// Generated by: Catalyze AI System
// Timestamp: {datetime.now().isoformat()}
// Operations: {', '.join(operations) if operations else 'Basic liquid handling'}
// ============================================================================

// Current Physical Layout:
// Box A = Loc_01, Box B = Loc_02, Box C = Loc_03
// Box D = Loc_07, Box E = Loc_08, Box F = Loc_09
// Consolidation Box = Loc_10
//
// Tip Box Plate Names:
// Box A (Loc_01) → DDX-96-200F_05
// Box B (Loc_02) → DDX-96-200F_06  
// Box C (Loc_03) → DDX-96-200F_04
// Box D (Loc_07) → DDX-96-200F_08
// Box E (Loc_08) → DDX-96-200F_01
// Box F (Loc_09) → DDX-96-200F_03
// Consolidation (Loc_10) → DDX-96-200F_02
// ============================================================================

public class {self._sanitize_class_name(title)} : IMMScriptExecutor
{{
    private readonly char[] rows = {{ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H' }};

    // Centralized method for location-to-plate mapping
    private string GetTipBoxPlate(string location)
    {{
        switch (location)
        {{
            case "Loc_01": return "DDX-96-200F_05";  // Box A
            case "Loc_02": return "DDX-96-200F_06";  // Box B
            case "Loc_03": return "DDX-96-200F_04";  // Box C
            case "Loc_07": return "DDX-96-200F_08";  // Box D
            case "Loc_08": return "DDX-96-200F_01";  // Box E
            case "Loc_09": return "DDX-96-200F_03";  // Box F
            default: return "DDX-96-200F_02";        // Consolidation box (Loc_10)
        }}
    }}

    public void Execute(IMMApp app)
    {{
        // Initialize protocol variables
        InitializeProtocolVariables(app);
        
        // Execute protocol steps
        ExecuteProtocolSteps(app);
        
        // Cleanup and finalize
        FinalizeProtocol(app);
    }}

    private void InitializeProtocolVariables(IMMApp app)
    {{
        // Set basic protocol information
        app.SetVariable("ProtocolName", "{title}");
        app.SetVariable("ProtocolDescription", "{description}");
        app.SetVariable("GeneratedBy", "Catalyze AI System");
        app.SetVariable("GenerationTime", "{datetime.now().isoformat()}");
        
        // Set default tip box configuration
        app.SetVariable("DefaultTipBox", "DDX-96-200F_05");
        app.SetVariable("ConsolidationBox", "DDX-96-200F_02");
        app.SetVariable("ConsolidationLocation", "Loc_10");
        
        // Set liquid handling parameters
        app.SetVariable("DefaultVolume", "100"); // Default 100μL
        app.SetVariable("DefaultSpeed", "50");   // Default speed
        app.SetVariable("DefaultHeight", "2");   // Default height above well
    }}

    private void ExecuteProtocolSteps(IMMApp app)
    {{
        // Protocol execution based on detected operations
        var operations = new List<string> {{ {', '.join([f'"{op}"' for op in operations]) if operations else '"basic_liquid_handling"'} }};
        
        foreach (var operation in operations)
        {{
            switch (operation)
            {{
                case "liquid_transfer":
                    ExecuteLiquidTransfer(app);
                    break;
                case "tip_handling":
                    ExecuteTipHandling(app);
                    break;
                case "plate_handling":
                    ExecutePlateHandling(app);
                    break;
                case "mixing":
                    ExecuteMixing(app);
                    break;
                default:
                    ExecuteBasicOperation(app, operation);
                    break;
            }}
        }}
    }}

    private void ExecuteLiquidTransfer(IMMApp app)
    {{
        // Liquid transfer operations
        app.SetVariable("TransferVolume", "100");
        app.SetVariable("SourcePlate", "Source_Plate");
        app.SetVariable("DestinationPlate", "Destination_Plate");
        app.SetVariable("TransferSpeed", "50");
        
        // Log the operation
        Console.WriteLine("Executing liquid transfer operation...");
        Console.WriteLine($"Transfer Volume: {{app.GetVariable("TransferVolume")}}μL");
        Console.WriteLine($"Source: {{app.GetVariable("SourcePlate")}}");
        Console.WriteLine($"Destination: {{app.GetVariable("DestinationPlate")}}");
    }}

    private void ExecuteTipHandling(IMMApp app)
    {{
        // Tip handling operations
        app.SetVariable("TipPickupLocation", "Loc_01");
        app.SetVariable("TipEjectLocation", "Loc_10");
        app.SetVariable("TipCount", "8");
        
        // Log the operation
        Console.WriteLine("Executing tip handling operation...");
        Console.WriteLine($"Pickup Location: {{app.GetVariable("TipPickupLocation")}}");
        Console.WriteLine($"Eject Location: {{app.GetVariable("TipEjectLocation")}}");
        Console.WriteLine($"Tip Count: {{app.GetVariable("TipCount")}}");
    }}

    private void ExecutePlateHandling(IMMApp app)
    {{
        // Plate handling operations
        app.SetVariable("PlateLocation", "Loc_01");
        app.SetVariable("PlateType", "96-well");
        app.SetVariable("PlateHeight", "10");
        
        // Log the operation
        Console.WriteLine("Executing plate handling operation...");
        Console.WriteLine($"Plate Location: {{app.GetVariable("PlateLocation")}}");
        Console.WriteLine($"Plate Type: {{app.GetVariable("PlateType")}}");
    }}

    private void ExecuteMixing(IMMApp app)
    {{
        // Mixing operations
        app.SetVariable("MixVolume", "100");
        app.SetVariable("MixCycles", "3");
        app.SetVariable("MixSpeed", "100");
        
        // Log the operation
        Console.WriteLine("Executing mixing operation...");
        Console.WriteLine($"Mix Volume: {{app.GetVariable("MixVolume")}}μL");
        Console.WriteLine($"Mix Cycles: {{app.GetVariable("MixCycles")}}");
        Console.WriteLine($"Mix Speed: {{app.GetVariable("MixSpeed")}}");
    }}

    private void ExecuteBasicOperation(IMMApp app, string operation)
    {{
        // Generic operation handler
        app.SetVariable("CurrentOperation", operation);
        app.SetVariable("OperationStatus", "InProgress");
        
        Console.WriteLine($"Executing basic operation: {{operation}}");
    }}

    private void FinalizeProtocol(IMMApp app)
    {{
        // Protocol cleanup and finalization
        app.SetVariable("ProtocolStatus", "Completed");
        app.SetVariable("CompletionTime", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        
        Console.WriteLine("Protocol execution completed successfully.");
        Console.WriteLine($"Completion Time: {{app.GetVariable("CompletionTime")}}");
    }}

    // Helper method to sanitize class names
    private string SanitizeClassName(string name)
    {{
        return name.Replace(" ", "_").Replace("-", "_").Replace(".", "_");
    }}
}}'''

        return csharp_code
    
    def _sanitize_class_name(self, name: str) -> str:
        """Sanitize a name to be a valid C# class name"""
        import re
        # Remove invalid characters and replace with underscores
        sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', name)
        # Ensure it starts with a letter
        if sanitized and not sanitized[0].isalpha():
            sanitized = 'Protocol_' + sanitized
        return sanitized or 'GeneratedProtocol'
