"""
Mode Processor

Handles mode-specific processing logic and provides utilities for
different agent modes and their specialized workflows.
"""

from typing import Dict, Any, List, Optional
from enum import Enum


class AgentMode(Enum):
    """Enumeration of available agent modes"""
    RESEARCH = "research"
    PROTOCOL = "protocol"
    AUTOMATE = "automate"
    SAFETY = "safety"


class ModeProcessor:
    """Processes queries based on specific agent modes"""
    
    def __init__(self):
        self.mode_configs = {
            AgentMode.RESEARCH: {
                "keywords": ["what is", "explain", "tell me about", "how does", "why", "properties", "structure", "formula"],
                "focus": "chemistry research and explanations",
                "output_format": "detailed_explanation"
            },
            AgentMode.PROTOCOL: {
                "keywords": ["protocol", "procedure", "steps", "method", "experiment", "synthesis", "reaction"],
                "focus": "lab protocols and procedures", 
                "output_format": "structured_protocol"
            },
            AgentMode.AUTOMATE: {
                "keywords": ["automate", "script", "robot", "opentrons", "pyhamilton", "automation", "write code", "generate code", "create code", "code for", "pipette", "liquid handling"],
                "focus": "lab automation scripts",
                "output_format": "python_code"
            },
            AgentMode.SAFETY: {
                "keywords": ["safety", "hazard", "dangerous", "toxic", "flammable", "corrosive", "risk"],
                "focus": "safety analysis and hazards",
                "output_format": "safety_assessment"
            }
        }
    
    def validate_mode(self, mode: str) -> AgentMode:
        """Validate and normalize the mode string"""
        try:
            return AgentMode(mode.lower())
        except ValueError:
            return AgentMode.RESEARCH  # Default fallback
    
    def get_mode_config(self, mode: AgentMode) -> Dict[str, Any]:
        """Get configuration for a specific mode"""
        return self.mode_configs.get(mode, self.mode_configs[AgentMode.RESEARCH])
    
    def enhance_query_for_mode(self, query: str, mode: AgentMode) -> str:
        """Enhance the query with mode-specific context"""
        config = self.get_mode_config(mode)
        
        mode_prompts = {
            AgentMode.RESEARCH: f"Please provide a detailed chemistry research explanation for: {query}",
            AgentMode.PROTOCOL: f"Generate a comprehensive lab protocol for: {query}",
            AgentMode.AUTOMATE: f"Create an automation script for: {query}",
            AgentMode.SAFETY: f"Provide a safety analysis for: {query}"
        }
        
        return mode_prompts.get(mode, query)
    
    def extract_mode_from_query(self, query: str) -> Optional[AgentMode]:
        """Extract the intended mode from the query content"""
        query_lower = query.lower()
        
        # Check for explicit mode indicators
        mode_indicators = {
            AgentMode.PROTOCOL: ["protocol", "procedure", "steps", "method", "experiment"],
            AgentMode.AUTOMATE: ["automate", "script", "robot", "opentrons", "pyhamilton", "write code", "generate code", "create code", "code for", "pipette", "liquid handling"],
            AgentMode.SAFETY: ["safety", "hazard", "dangerous", "toxic", "risk"],
            AgentMode.RESEARCH: ["what is", "explain", "tell me about", "how does", "why"]
        }
        
        # Count matches for each mode
        mode_scores = {}
        for mode, indicators in mode_indicators.items():
            score = sum(1 for indicator in indicators if indicator in query_lower)
            if score > 0:
                mode_scores[mode] = score
        
        # Return the mode with the highest score
        if mode_scores:
            return max(mode_scores, key=mode_scores.get)
        
        return None
    
    def format_response_for_mode(self, response: str, mode: AgentMode) -> str:
        """Format the response according to mode-specific requirements"""
        config = self.get_mode_config(mode)
        
        if mode == AgentMode.PROTOCOL:
            return self._format_protocol_response(response)
        elif mode == AgentMode.AUTOMATE:
            return self._format_automation_response(response)
        elif mode == AgentMode.SAFETY:
            return self._format_safety_response(response)
        else:
            return response  # Research mode - no special formatting
    
    def _format_protocol_response(self, response: str) -> str:
        """Format response as a structured protocol"""
        # Add protocol-specific formatting
        if "##" not in response and "#" not in response:
            # Add basic structure if not present
            formatted = f"# Lab Protocol\n\n{response}\n\n---\n*Generated by Catalyze Protocol Agent*"
            return formatted
        return response
    
    def _format_automation_response(self, response: str) -> str:
        """Format response as automation code"""
        # Ensure code blocks are properly formatted
        if "```python" not in response and "```" not in response:
            # Add code block formatting if not present
            formatted = f"```python\n{response}\n```\n\n*Generated by Catalyze Automate Agent*"
            return formatted
        return response
    
    def _format_safety_response(self, response: str) -> str:
        """Format response as safety assessment"""
        # Add safety-specific formatting
        if "⚠️" not in response and "🚨" not in response:
            # Add safety indicators if not present
            formatted = f"🛡️ **Safety Analysis**\n\n{response}\n\n---\n*Generated by Catalyze Safety Agent*"
            return formatted
        return response
    
    def get_mode_statistics(self) -> Dict[str, Any]:
        """Get statistics about mode usage and configuration"""
        return {
            "total_modes": len(self.mode_configs),
            "available_modes": [mode.value for mode in AgentMode],
            "mode_configs": {
                mode.value: {
                    "keywords_count": len(config["keywords"]),
                    "focus": config["focus"],
                    "output_format": config["output_format"]
                }
                for mode, config in self.mode_configs.items()
            }
        }
